{
  imports = [
    ./aria2.nix
    ./bash.nix
    ./bat.nix
    ./btop.nix
    ./burpsuite.nix
    ./cava.nix
    ./delta.nix
    ./discord.nix
    ./elyprismlauncher.nix
    ./emacs.nix
    ./fastfetch.nix
    ./fd.nix
    ./firefox.nix
    ./foot.nix
    ./fuzzel.nix
    ./fzf.nix
    ./gh.nix
    ./git.nix
    ./gpg-agent.nix
    ./gpg.nix
    ./imv.nix
    ./lf.nix
    ./mango.nix
    ./mcp.nix
    ./mpv.nix
    ./ncmpcpp.nix
    ./neovim.nix
    ./noctalia.nix
    ./npm.nix
    ./obs-studio.nix
    ./opencode.nix
    ./password-store.nix
    ./ripgrep.nix
    ./satty.nix
    ./ssh.nix
    ./tealdeer.nix
    ./tmux.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
