#!/bin/sh

set -eu

HERE="$(dirname "$(readlink -f "$0")")"
. "$HERE/.config/shell/env"

SETUP_PROGRAMS_DIR="${SETUP_PROGRAMS_DIR:-$HOME/programs}"
SETUP_PKGS_FILE="${SETUP_PKGS_FILE:-$XDG_DATA_HOME/meta/pkgs.txt}"
SETUP_PKGS_FLATPAKS_FILE="${SETUP_PKGS_FLATPAKS_FILE:-$XDG_DATA_HOME/meta/flatpaks.txt}"
SETUP_PKGS_GO_FILE="${SETUP_PKGS_GO_FILE:-$XDG_DATA_HOME/meta/pkgs_go.txt}"

[ -n "${SETUP_BROWSER_DIR:-}" ] || case "$BROWSER" in
	zen-browser) SETUP_BROWSER_DIR="$HOME/.zen" ;;
	librewolf) SETUP_BROWSER_DIR="$HOME/.librewolf" ;;
	waterfox) SETUP_BROWSER_DIR="$HOME/.waterfox" ;;
	firefox) SETUP_BROWSER_DIR="$HOME/.mozilla/firefox" ;;
	*)
		[ "$1" = "browser" ] || [ "$1" = "all" ] && {
			echo "$(basename "$0"): cannot determine SETUP_BROWSER_DIR" >&2
			exit 1
		}
		;;
esac

# shellcheck disable=2015
sudocmd="$([ -s /etc/doas.conf ] && command -v doas 2>/dev/null || command -v sudo 2>/dev/null)"

[ "$(id -u)" -eq 0 ] && {
	echo "$(basename "$0"): this script should not run as root" >&2
	exit 1
}

setup_dotfiles() {
	cp -srvft "$HOME" "$HERE/.config" "$HERE/.local"
	ln -svf "$XDG_CONFIG_HOME/shell/profile" "$HOME/.zprofile"
	[ -d "$HERE/etc" ] &&
		$sudocmd cp --preserve=mode,links,timestamp -rfvt /etc "$HERE/etc/." ||
		true
	[ -d "$HERE/usr" ] &&
		$sudocmd cp --preserve=mode,links,timestamp -rfvt /usr "$HERE/usr/." ||
		true
	[ -x /usr/local/bin/pinentry-fuzzel ] &&
		$sudocmd ln -sfv /usr/local/bin/pinentry-fuzzel /usr/bin/pinentry
	[ -n "${WINEPREFIX:-}" ] &&
		command -v wine >/dev/null 2>&1 &&
		mkdir -pv "$WINEPREFIX"
	command -v gsettings >/dev/null 2>&1 &&
		gsettings set org.gnome.desktop.interface color-scheme prefer-dark &&
		[ -n "${GTK_THEME:-}" ] &&
		gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
}

setup_pkgs() {
	$sudocmd xbps-install -Sy && $sudocmd xbps-install -Suy xbps && $sudocmd xbps-install -Suy
	[ -r "$SETUP_PKGS_FILE" ] &&
		xargs "$sudocmd" xbps-install -Sy <"$SETUP_PKGS_FILE"
	[ -r "$SETUP_PKGS_FLATPAKS_FILE" ] &&
		command -v flatpak >/dev/null 2>&1 &&
		flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo &&
		xargs flatpak install -y <"$SETUP_PKGS_FLATPAKS_FILE"
	command -v go >/dev/null 2>&1 &&
		go telemetry off &&
		xargs -a ~/.local/share/meta/pkgs_go.txt -I {} go install -v {}
	curl https://raw.githubusercontent.com/jarun/advcpmv/master/install.sh --create-dirs -o $XDG_CACHE_HOME/advcpmv/install.sh && (cd $XDG_CACHE_HOME/advcpmv && sh install.sh)
}

setup_user() {
	[ -r "$XDG_CONFIG_HOME/user-dirs.dirs" ] &&
		cut -d "=" -f2 <"$XDG_CONFIG_HOME/user-dirs.dirs" |
		sed -e "s|\$HOME|$HOME|" |
		xargs mkdir -pv &&
		command -v xdg-user-dirs-update >/dev/null 2>&1 &&
		xdg-user-dirs-update ||
		true
	chsh -s "$(which zsh)"
	$sudocmd usermod -aG video,audio,input,storage,optical,network,lp,scanner,dbus,adbusers,dbus,wireshark,nixbld,socklog,libvirt,docker,wheel "$USER"
}

setup_runit() {
	$sudocmd rm -vf \
		/var/service/agetty-tty4 \
		/var/service/agetty-tty5 \
		/var/service/agetty-tty6 \
		/var/service/acpid \
		/var/service/wpa_supplicant ||
		true
	$sudocmd ln -svft /var/service \
		/etc/sv/socklog-unix \
		/etc/sv/nanoklogd \
		/etc/sv/dbus \
		/etc/sv/udevd \
		/etc/sv/chronyd \
		/etc/sv/cronie \
		/etc/sv/elogind \
		/etc/sv/dhcpcd \
		/etc/sv/iwd \
		/etc/sv/bluetoothd \
		/etc/sv/ufw \
		/etc/sv/tlp \
		/etc/sv/sshd \
		/etc/sv/cupsd \
		/etc/sv/zramen \
		/etc/sv/libvirtd \
		/etc/sv/virtlogd \
		/etc/sv/vnstatd \
		/etc/sv/waydroid-container \
		/etc/sv/rtkit
}

setup_ufw() {
	$sudocmd ufw default deny incoming
	$sudocmd ufw default allow outgoing
	$sudocmd ufw limit ssh
	$sudocmd ufw allow in proto udp from 172.16.0.0/12 to 172.17.0.1 port 53 comment "allow-docker-dns"
	$sudocmd ufw route allow in on virbr0
	$sudocmd ufw route allow in on waydroid0
}

setup_pam() {
	grep -Fq "pam_ssh.so" /etc/pam.d/login || {
		cat <<-_EOF | $sudocmd tee -a /etc/pam.d/login >/dev/null

			-auth optional pam_ssh.so try_first_pass
			-session optional pam_ssh.so
		_EOF
	}
}

setup_browser() {
	[ -d "$SETUP_PROGRAMS_DIR/arkenfox-user.js" ] ||
		git clone https://github.com/arkenfox/user.js.git "$SETUP_PROGRAMS_DIR/arkenfox-user.js"
	git -C "$SETUP_PROGRAMS_DIR/arkenfox-user.js" pull --rebase
	[ -d "$SETUP_BROWSER_DIR" ] || {
		$BROWSER --headless >/dev/null 2>&1 &
		ffpid=$!
		sleep 1
	}
	sed -n "/Default=.*\..*/s/.*=//p" "$SETUP_BROWSER_DIR/profiles.ini" |
		while IFS= read -r p; do
			cp -vf "$SETUP_PROGRAMS_DIR/arkenfox-user.js/user.js" "$SETUP_BROWSER_DIR/$p/user.js"
			browsers="firefox"
			# shellcheck disable=2015
			[ "$BROWSER" != "$browsers" ] && browsers="$browsers $BROWSER" || true
			for b in $browsers; do
				[ -r "$XDG_CONFIG_HOME/$b/user.js" ] &&
					cat "$XDG_CONFIG_HOME/$b/user.js" >>"$SETUP_BROWSER_DIR/$p/user.js"
				[ -d "$XDG_CONFIG_HOME/$b/chrome" ] &&
					cp -rvL "$XDG_CONFIG_HOME/$b/chrome" "$SETUP_BROWSER_DIR/$p"
			done
		done
	# shellcheck disable=2015
	[ -n "${ffpid:-}" ] && kill "$ffpid" || true
}

setup_install() {
	setup_dotfiles
	setup_pkgs
	setup_user
	setup_runit
	setup_ufw
	setup_pam
	setup_browser
}

setup_uninstall() {
	find "$HERE/.config" "$HERE/.local" -type f |
		while IFS= read -r p; do
			f="${p#"$HERE/"}"
			# shellcheck disable=2015
			[ -L "$HOME/$f" ] &&
				[ "$HERE/$f" = "$(readlink -f "$HOME/$f")" ] ||
				continue
			rm -vf "$HOME/$f"
		done
	sed -n "/Default=.*\..*/s/.*=//p" "$SETUP_BROWSER_DIR/profiles.ini" |
		while IFS= read -r p; do
			# shellcheck disable=2015
			[ -r "$SETUP_BROWSER_DIR/$p/user.js" ] &&
				cat "/usr/share/arkenfox-user.js/user.js" "$XDG_CONFIG_HOME/firefox/user.js" "$XDG_CONFIG_HOME/$BROWSER/user.js" |
				cmp "$SETUP_BROWSER_DIR/$p/user.js" ||
				continue
			rm -vf "$SETUP_BROWSER_DIR/$p/user.js"
		done
}

case "${1:-dotfiles}" in
	install) setup_install ;;
	dotfiles) setup_dotfiles ;;
	pkgs) setup_pkgs ;;
	user) setup_user ;;
	runit) setup_runit ;;
	ufw) setup_ufw ;;
	pam) setup_pam ;;
	browser) setup_browser ;;
	uninstall) setup_uninstall ;;
	*)
		echo "$(basename "$0"): unknown command \"$1\"" >&2
		exit 1
		;;
esac
