#!/bin/sh

HERE="$(dirname "$(readlink -f "$0")")"
. "$HERE/.config/shell/env"

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
SETUP_PROGRAMS_DIR="${SETUP_PROGRAMS_DIR:-$HOME/programs}"
SETUP_PKGS_FILE="${SETUP_PKGS_FILE:-$XDG_DATA_HOME/pkgs/pkgs.txt}"
SETUP_PKGS_AUR_FILE="${SETUP_PKGS_AUR_FILE:-$XDG_DATA_HOME/pkgs/pkgs_aur.txt}"

# shellcheck disable=2015
sudocmd="$([ -s /etc/doas.conf ] && command -v doas 2>/dev/null || command -v sudo 2>/dev/null)"
browserdir="$HOME/.mozilla/firefox"

[ "$(id -u)" -eq 0 ] && {
	echo "$(basename "$0"): this script should not run as root" >&2
	exit 1
}

setup_dotfiles() {
	cp -srvft "$HOME" "$HERE/.config" "$HERE/.local"
	ln -svf "$XDG_CONFIG_HOME/shell/profile" "$HOME/.zprofile"
	$sudocmd cp -rvf "$HERE/etc/." /etc
	$sudocmd cp -afvt /etc /usr/share/pipewire /usr/share/wireplumber
}

setup_pkgs() {
	$sudocmd pacman -Syu --no-confirm
	$sudocmd pacman -S --needed --noconfirm artix-archlinux-support &&
		$sudocmd pacman-key --populate archlinux &&
		$sudocmd pacman -Sy --noconfirm
	[ -s "$SETUP_PKGS_FILE" ] &&
		sudocmd pacman -S --needed --noconfirm - < "$SETUP_PKGS_FILE"
	[ -s "$SETUP_PKGS_AUR_FILE" ] && {
			git clone https://aur.archlinux.org/paru.git "$SETUP_PROGRAMS_DIR/paru" &&
				makepkg -siD "$SETUP_PROGRAMS_DIR/paru"
		}
		paru -Sa --needed --noconfirm --sudo "$sudocmd" - <"$SETUP_PKGS_AUR_FILE"
}

setup_user() {
	chsh -s "$(which zsh)"
	$sudocmd ln -sfT dash /usr/bin/sh
	$sudocmd usermod -aG video,audio,input,power,storage,optical,lp,scanner,dbus,docker,adbusers,uucp "$USER"
}

setup_runit() {
	doas rm -vf \
		/run/runit/service/agetty-tty4 \
		/run/runit/service/agetty-tty5 \
		/run/runit/service/agetty-tty6
	doas ln -svft /run/runit/service \
		/etc/runit/sv/socklog \
		/etc/runit/sv/klog \
		/etc/runit/sv/dbus \
		/etc/runit/sv/udevd \
		/etc/runit/sv/chrony \
		/etc/runit/sv/elogind \
		/etc/runit/sv/dhcpcd \
		/etc/runit/sv/wpa_supplicant \
		/etc/runit/sv/bluetoothd \
		/etc/runit/sv/cronie \
		/etc/runit/sv/tlp \
		/etc/runit/sv/sshd \
		/etc/runit/sv/docker
}

setup_firefox() {
	[ -d "$browserdir" ] ||
		{ firefox --headless >/dev/null 2>&1 & ffpid=$!; sleep 1; }
	profile="$(sed -n "/Default=.*\..*/s/.*=//p" "$browserdir/profiles.ini")"
	curl -sL https://raw.githubusercontent.com/arkenfox/user.js/master/user.js |
		cat - "$XDG_CONFIG_HOME/firefox/user.js" >"$browserdir/$profile/user.js"
	# shellcheck disable=SC2015
	[ -n "$ffpid" ] && pkill firefox || true
}

clean() {
	cd "$HERE" || exit 1
	find .config .local -type f -exec rm -vf "$HOME/{}" \;
	profile="$(sed -n "/Default=.*\..*/s/.*=//p" "$browserdir/profiles.ini")"
	[ -s "$browserdir/$profile/user.js" ] && rm -vf "$browserdir/$profile/user.js"
}

case "$1" in
	""|all)
		setup_dotfiles
		setup_pkgs
		setup_user
		setup_runit
		setup_firefox
		;;
	dotfiles) setup_dotfiles ;;
	pkgs) setup_pkgs ;;
	user) setup_user ;;
	runit) setup_runit ;;
	firefox) setup_firefox ;;
	clean) clean ;;
	*)
		echo "$(basename "$0"): unknown command \"$1\"" >&2
		exit 1
		;;
esac
