#!/bin/sh

alias g="git"
alias gst="git status -sb"
alias gph="git push"
alias gpl="git pull"
alias gdf="git diff"

command -v bicon >/dev/null 2>&1 && {
	alias yazi="bicon.bin yazi"
	alias ncmpcpp="bicon.bin ncmpcpp"
}

alias info="info --vi-keys"
alias ccat="highlight -O ansi"
alias urls="rg '(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:;a-zA-Z0-9./+@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)'"
alias bm="buku --suggest"
