#!/bin/sh

unsetopt PROMPT_SP 2>/dev/null

alias e="${EDITOR:-vi}"
alias q="exit"

alias mkd="mkdir -pv"
alias cp="cp -iv"
alias ln="ln -iv"
alias mv="mv -iv"
alias rm="rm -Iv"
alias ls="ls -hF --color=auto --group-directories-first"
alias ll="ls -lA"
alias grep="grep --color=auto"
alias gr="grep --exclude-dir={.git,node_modules} -Hnr"

alias g="git"
alias gst="git status -sb"
alias gph="git push"
alias gpl="git pull"
alias gdf="git diff"

alias ip="ip -color=auto"
alias bc="bc -ql"
alias nnn="nnn -Rr"
alias diff="diff --color=auto"
alias info="info --vi-keys"
alias ccat="highlight -O ansi"
alias rsync="rsync -vrPlu"
alias ffmpeg="ffmpeg -hide_banner"
alias urls="rg '(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:;a-zA-Z0-9./+@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)'"
alias bm="buku --suggest"
alias drag="dragon-drop -a -x"
alias adb='env HOME="$ANDROID_USER_HOME" adb'
alias mitmproxy='mitmproxy --set confdir="$XDG_CONFIG_HOME/mitmproxy"'
alias mitmweb='mitmweb --set confdir="$XDG_CONFIG_HOME/mitmproxy"'
alias msfconsole='msfconsole -q'

# pacman
alias pi="doas pacman -S"
alias pu="doas pacman -Syu"
alias pr="doas pacman -Rns"
alias pq="pacman -Ss"
alias pql="pacman -Qs"
alias plu="pacman -Qqen > ~/.dotfiles/.local/share/meta/pkgs.txt; pacman -Qqem | rg -v -w 'paru|packettracer'> ~/.dotfiles/.local/share/meta/pkgs_aur.txt"

# neovim for vim if available
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

sudocmd="$(command -v doas 2>/dev/null || command -v sudo 2>/dev/null)"
for cmd in su mount umount sv updatedb rsm ufw openvpn; do
	alias $cmd="$sudocmd $(which "$cmd")"
done
unset sudocmd cmd
