#!/bin/sh

# shellcheck disable=SC1091
. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env"

[ -z "${DISPLAY:-${WAYLAND_DISPLAY:-}}" ] &&
	[ "$(tty)" = "/dev/tty1" ] &&
	exec ssh-agent dbus-run-session niri --session
